### ISSUE TITLE
Nested project/manifest files

### ISSUE THREAD

**Issue by Alim-faraji** [QuantEcon/lecture-julia.myst#10]
Look at https://github.com/executablebooks/jupyter-cache/issues/67#issue-910095650. We need a way to put those file in subfolders.

**Comment by mmcky** [comment]
@Alim-faraji these should work -- as `jupyter-cache` by default actually executes in the context of the source directories. Let me know if this isn't working for you.

**Comment by jlperla** [comment]
I think we will stick with a mono-manifest for the foreseeable future.
