### ISSUE TITLE
Remove panels and static from the notebook repository

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#107]
See https://github.com/QuantEcon/lecture-julia.notebooks

We should not be deploying:
- [ ] https://github.com/QuantEcon/lecture-julia.notebooks/tree/main/_panels_static
- [ ] https://github.com/QuantEcon/lecture-julia.notebooks/tree/main/_static

All static files should references to the web, etc.  Otherwise, the notebooks can't work 

@mmcky  Is this something easy to do, or maybe it is even complete (since we haven't deployed it recently)?

**Comment by mmcky** [comment]
👍 we can just update the `sync` script. I can handle this one.
