### ISSUE TITLE
Add .gitignore to the notebook repo

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#108]
The immediate things to add are:
```
.DS_Store
**/.ipynb_checkpoints
.vscode/settings.json
```
Can we just put it in https://github.com/QuantEcon/lecture-julia.myst/tree/main/_notebook_repo  and have it automatically deploy, or is there a step required?

**Comment by mmcky** [comment]
ah you want this for notebooks repo? OK -- will update.

**Comment by mmcky** [comment]
closed by e2f7253
