### ISSUE TITLE
Lecture on debugging

### ISSUE THREAD

**Issue by DawievLill** [QuantEcon/lecture-julia.myst#130]
I have gone through the lectures on software engineering and they are incredibly useful to establish a good workflow. I think if people work through these lectures they will be nicely set up to start working on their own code and even to develop their own packages in Julia (which is really easy in comparison to Python!). 

The one thing that might be nice to see is some discussion on debugging in Julia. This will be nice for people coming from Python and especially Matlab. I know this is a killer feature for many of my colleagues in Matlab, which is actually preventing them from using Julia. 

Would it be worthwhile to have such a discussion in the lectures? Or is the debugging in Julia / VS Code not at the level where it is something we would like to advertise? 

If there is some discussion in the lectures on this already you can ignore the issue. 

I would be happy to help in writing some of the basic content for this, which others can then extend.

**Comment by jlperla** [comment]
https://julia.quantecon.org/software_engineering/tools_editors.html#using-the-debugger


There is some, but I am not sure the debugger should be pushed. It just isn't anything like the matlab or python debuggers, sadly. There are a variety of reasons why, but that is the current state.

I will add in #129 at some point to this.
