### ISSUE TITLE
LightGraphs -> Graphs transition

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#134]
See https://discourse.julialang.org/t/lightgraphs-jl-transition/69526

We need to get rid of LightGraphs from the project/manifest, add in Graphs, and hopefully the only other change is to change `using LightGraphs` to `using Graphs`

**Comment by jlperla** [comment]
@jbrightuniverse i think things may be stable enough to try this now

**Comment by jbrightuniverse** [comment]
@jlperla some other packages we're using still have LightGraphs as a dependency (`QuantEcon`, for example), which means it can't remove itself from the manifest (but it does remove itself from project).

**Comment by jlperla** [comment]
@jbrightuniverse   Thanks.  Getting it out of the project is good enough.

As posted on slack, maybe you can put in the PR to fix up QuantEcon.jl?  Lower priority though

For the other packages, I think it is totally fine for them to upgrade at their own rate.  It isn't a big problem to have it around, we just don't want to tel lpeople to use it directly.
