### ISSUE TITLE
Test on Julia 1.7

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#139]
@jbrightuniverse I think that it might be time to try thkngs out with Julia 1.7

If it works, we can bump manifest versions of all packages with a `] up` while we are at it.

The only hesitation is that it sometimes takes packages a little time to catch up with new versions, so it is possible there are problems. But I think it is worth trying on a branch

**Comment by jbrightuniverse** [comment]
@jlperla for the most part, nothing produces any errors under 1.7 and updated packages except for the following in Generic Programming:
![image](https://user-images.githubusercontent.com/30967260/148704366-a7d3a02e-a9aa-42e7-9aa5-688fd6be51c2.png)
A fix is to change `Distributions.pdf(d::OurTruncatedExponential, x)` to `Distributions.pdf(d::OurTruncatedExponential, x::real)` where it appears.

There is also a
```
Warning: The active manifest file is an older format with no julia version entry. Dependencies may have been resolved with a different julia version.
```
I'm not sure how to resolve that yet.

**Comment by jlperla** [comment]
Great! That manifest thjng will go away after you do a package operation. Since we would want to bump package versions with the upgrade it should resolve itself.
My only concern for this is that I don't think the CI is correctly capturing things because of #84 so we would need to be super careful on the output here. @mmcky not sure what the plan was for that stuff

**Comment by mmcky** [comment]
@jlperla it looks like Alim fixed that issue based on the last comment. I'll re-run the PR enabling warnings and see if can enable those safeguards now.
