### ISSUE TITLE
broken doc syntax

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-julia.myst#140]
See `{doc}` in 38.1 of https://julia.quantecon.org/dynamic_programming/ifp.html

**Comment by jlperla** [comment]
@jbrightuniverse take a look when you get a chance

**Comment by jbrightuniverse** [comment]
Tentatively, I think the problem was that the string associated with `{doc}` was broken onto two lines. When I moved them onto one line (after recompiling the notebooks with the original setup to reproduce the bug), it appeared normally.

**Comment by jbrightuniverse** [comment]
Fix is now published.
