### ISSUE TITLE
numbered bullet points do not always increment in generated notebooks

### ISSUE THREAD

**Issue by jbrightuniverse** [QuantEcon/lecture-julia.myst#153]
For example, see the `getting_started` lecture. In the source, we have:
```
### Install Julia

After Conda is installed, you can install Julia.

1. Download and install Julia, from [download page](http://julialang.org/downloads/), accepting all default options.  
1. Open Julia, by either  
  - Navigating to Julia through your menus or desktop icons (Windows, Mac), or  
  - Opening a terminal and type `julia` (Linux; to set this up on macOS, see [here](https://julialang.org/downloads/platform/#macos)).  
  You should now be looking at something like this  
  ![https://julia.quantecon.org/_static/figures/julia_term_1.png](https://julia.quantecon.org/_static/figures/julia_term_1.png)
  
    
  This is called the JULIA *REPL* (Read-Evaluate-Print-Loop), which we discuss more [later](https://julia.quantecon.org/../software_engineering/tools_editors.html#repl-main).  
1. In the Julia REPL, hit `]` to enter package mode and then enter: 
```
all of these display as 1s, which is incorrect. This does not happen in the published version: https://julia.quantecon.org/getting_started_julia/getting_started.html#install-julia

When rendering the block in jupyterlab, the following happens:
![image](https://user-images.githubusercontent.com/30967260/152072506-1b4e4a2b-d157-49fc-98f1-3a33fac87c17.png)
Adjacent bullet points increment, but non-adjacent bullet points remain at their original 1 label. This also happens when using separate cells for each bullet point despite the numbers displaying as normal in the published web lectures.

**Comment by jlperla** [comment]
Seems fixed
