### ISSUE TITLE
GitHub - Issue with QuantEcon Services PAT

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-julia.myst#156]
GitHub -- Please stop changing your security so dang frequently!

Looks like I will need to reissue a QuantEcon Services PAT key for automatic publishing of updated download notebooks to lecture-julia.notebooks.

**Comment by mmcky** [comment]
Not sure why this failed as the `PAT` is working on `python` sites. Will keep this open and check when the next publish happens.

**Comment by mmcky** [comment]
I have reset the `quantecon-services` access on the `lecture-julia.notebooks` repo to see if that helps.

**Comment by mmcky** [comment]
If this persists I will:
- [ ] disable automatic notebook publish
- [ ] add some notes to publish notebooks
- [ ] look at more robust solutions for all `QuantEcon` projects

**Comment by jlperla** [comment]
@mmcky   I am going through issues to see which ones are essential and which we can clean up.  Is this one an issue we can close?

**Comment by jlperla** [comment]
Hi @mmcky   Looks like we can close this one?
