### ISSUE TITLE
3.8.1. Exercise 1 Part 3: pairs is a function in Base module

### ISSUE THREAD

**Issue by wendingliu** [QuantEcon/lecture-julia.myst#161]
The exercise asks to create a tuple named **pairs**, but trying to create _pairs = ((2, 5), (4, 2), (9, 8), (12, 10))_ as in the solution will generate the error message "cannot assign a value to variable Base.pairs from module Main".  Thus, the exercise might need to be modified.

**Comment by jlperla** [comment]
Ah thanks, we will fix!
