### ISSUE TITLE
StatsPlots and Plots simultaneously imported in some lectures

### ISSUE THREAD

**Issue by jbrightuniverse** [QuantEcon/lecture-julia.myst#178]
Every lecture that uses `StatsPlots` simultaneously includes the baseline `Plots` library as well. I think that including just the former is enough to bring the attributes of the latter into the namespace so this might actually be detrimental if it ends up loading twice? But I am not sure if it actually does.

**Comment by jlperla** [comment]
Closing.  Probably better to leave things more explicit, especially if StatsPlots has a major rewrite and stops reexporting (which is usually a bad idea)
