### ISSUE TITLE
Current Warnings need to be Resolved

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-julia.myst#18]
@Alim-faraji the following warnings will need to be resolved.

- [x] lecture-julia.myst/lectures/dynamic_programming/smoothing.md:65: WARNING: unknown document: dynamic_programming/perm_income_cons
- [x] lecture-julia.myst/lectures/dynamic_programming/smoothing.md:80: WARNING: unknown document: dynamic_programming/perm_income_cons
- [ ] lecture-julia.myst/lectures/getting_started_julia/getting_started.md:107: WARNING: 'myst' reference target not found: x-github-client://openRepo/https://github.com/QuantEcon/quantecon-notebooks-julia
- [x] lecture-julia.myst/lectures/more_julia/testing.md:538: WARNING: Could not lex literal_block as "julia". Highlighting skipped.
- [x] lecture-julia.myst/lectures/time_series_models/classical_filtering.md:392: WARNING: unknown document: time_series_models/lu_tricks
- [x] lecture-julia.myst/lectures/time_series_models/classical_filtering.md:578: WARNING: unknown document: time_series_models/lu_tricks
- [x] lecture-julia.myst/lectures/tools_and_techniques/kalman.md:464: WARNING: 'myst' reference target not found: 
- [x] lecture-julia.myst/lectures/tools_and_techniques/numerical_linear_algebra.md:43: WARNING: unknown document: ../getting_starting_julia/introduction_to_types
- [x] lecture-julia.myst/lectures/tools_and_techniques/numerical_linear_algebra.md:458: WARNING: undefined label: qr_decomposition
- [x] lecture-julia.myst/lectures/tools_and_techniques/numerical_linear_algebra.md:471: WARNING: undefined label: qr_decomposition
- [x] lecture-julia.myst/lectures/tools_and_techniques/numerical_linear_algebra.md:570: WARNING: unknown document: mc

**Comment by Alim-faraji** [comment]
>  lecture-julia.myst/lectures/getting_started_julia/getting_started.md:107: WARNING: 'myst' reference target not found: x-github-client://openRepo/https://github.com/QuantEcon/quantecon-notebooks-julia

I think it cannot find the reference target because `x-github-client` opens Github-desktop and it's not installed in the Runner.

**Comment by jlperla** [comment]
Yeah, the github desktop (and vscode spaces eventually) urls won't be something the runner can check. Can just those ones be ignored?

**Comment by Alim-faraji** [comment]
@mmcky can we tell jb to ignore checking reference targets?

**Comment by mmcky** [comment]
There is no mechanism at the moment to filter out warnings by type. 

Hmm ... will have a think through this. Is it a link to open GitHub Desktop locally?

**Comment by Alim-faraji** [comment]
> There is no mechanism at the moment to filter out warnings by type. 
> 
> 
> 
> Hmm ... will have a think through this. Is it a link to open GitHub Desktop locally?

Yes if you copy it in your browser it opens the GitHub desktop app.

**Comment by jlperla** [comment]
If this is breaking everything we can turn it off for now. Maybe make an issue for ignoring url prefix which are not http or https?  I can imagine all sorts of url prefixes for automatically launching stuff on desktops. Slack has one for example as well

**Comment by jlperla** [comment]
Also, I would Iove to do this : https://mobile.twitter.com/code/status/1425503238145650691

**Comment by mmcky** [comment]
thanks @Alim-faraji for fixing these up. 

I will remove the `-W --keep-going` but let's open an issue re: GitHub style links that issue warnings.

**Comment by Alim-faraji** [comment]
Let's instead keep this issue open.
