### ISSUE TITLE
Graph titles/graph layouts in some notebooks are malformed

### ISSUE THREAD

**Issue by jbrightuniverse** [QuantEcon/lecture-julia.myst#195]
Examples:

time_series_models/additive_functionals.md: several plots cut off at the top and to the right
time_series_models/multiplicative_functionals.md: plots at the end have overlapping titles and are cut off on the left and right sides

**Comment by jlperla** [comment]
Fixed everything that isn't a GR/etc. bug.  Cannot find workaround to add margins above figure.
