### ISSUE TITLE
Update `literalinclude` to `code-cell` with file loads

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-julia.myst#2]
For any `literalinclude` that is a file containing code it will need to be updated to:

````
```{code-cell} julia
:load: <filename.jl>
```
````

**Comment by Alim-faraji** [comment]
Do you think it should be done manually, or we can write a script to do this?

**Comment by Alim-faraji** [comment]
I think assuming sphynx-tomyst works well (which it does as in the datascience lectures), we need to do this update only once, so doing it manually makes sense.

**Comment by mmcky** [comment]
This is best done `manually` as there are some cases (typically) that are `code` files (that need executing) and some that are just demonstration files that you want shown on the site as raw text. 

Remember though to leave the PR open (in the short term) so we can apply `sphinx-tomyst` updates more easily to the `main` branch

**Comment by Alim-faraji** [comment]
I'm closing this issue, but I won't merge the `project/manifest` branch (which solves this) to the main branch.
