### ISSUE TITLE
Julia Setup

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-julia.myst#20]
The `julia` environment takes a long time to setup. 

Can the `julia` environment be cached? What is the default folder that we need to save?

**Comment by jlperla** [comment]
Everything should be in `.julia`

**Comment by mmcky** [comment]
When I run 

```
julia -e 'using Pkg; Pkg.activate("lectures"); Pkg.instantiate(); Pkg.add("IJulia");'
```

it modifies the `Manifest.toml` and `Project.toml` files. Is this expected?

Do we need to add this to `cache.yml` to keep these up to date?

**Comment by jlperla** [comment]
IJulia should be added separately, and without the activation of the project beforehand.

Also, that isn't the way to activate projects. You use the --project option to activate.

So something like
```bash
julia -e 'using Pkg; Pkg.add("IJulia");'
julia --project --threads auto -e 'using;Pkg;Pkg.instantiate();'
```

**Comment by mmcky** [comment]
OK -- thanks @jlperla I will update the `github action workflow`

**Comment by jlperla** [comment]
What I gave could have typos, on pjoje

**Comment by jlperla** [comment]
Before trying to cache things, I would see how large the .julia folder is. It might be enormous.

**Comment by mmcky** [comment]
I think I will leave it un-cached for now -- to ensure the software is up to date. The change to the `julia` commands above makes setup much quicker with a lot less packages installed for some reason.

**Comment by jlperla** [comment]
Yeah, the way you had it it would basically end up precompiling everything, changing a huge number of packages from the manifest, and then recompiling it all again.


I wouldn't worry about avoiding caching to ensure it keeps the software up to date. This will now use the manifest as a complete snapshot of everything...so the only way the cache could change would be if the manifest and package files were modified. It is using perfectly reproducible environments.

That said, there may be a better way to do that caching by package compiling everything into the Julia executable. Then it will be blindingly fast. We can try that later. @Alim did something related to that for a different project

**Comment by Alim-faraji** [comment]
I think you mean [PackageCompiler.jl](https://github.com/JuliaLang/PackageCompiler.jl)? That seems right to me.

**Comment by jlperla** [comment]
I will close.  We can add in new issues if there are specific things to change or tweak.
