### ISSUE TITLE
Missing Block of Code in Interacting with Julia Notebook

### ISSUE THREAD

**Issue by jbrightuniverse** [QuantEcon/lecture-julia.myst#23]
Edit: its the markdown file, not a notebook.

[This part of the file](https://github.com/QuantEcon/lecture-julia.myst/blob/main/lectures/getting_started_julia/julia_environment.md#plots) under Plots is missing a block of code after "Note that if you’re using a JupyterHub setup, you will need to first run"

```
using InstantiateFromURL
# optionally add arguments to force installation: instantiate = true, precompile = true
github_project("QuantEcon/quantecon-notebooks-julia", version = "0.8.0")
```

**Comment by jlperla** [comment]
The installation process will change in this version (and not have the InstantiateFromURL any longer). We can test after the notebooks are generated in a repo and you have conda
