### ISSUE TITLE
simulate not exported and therefore not available when using QuantEcon

### ISSUE THREAD

**Issue by orangebacked** [QuantEcon/lecture-julia.myst#273]
the function simulate  within src/markov/mc_tools.jl is not exported and therefore not available when using QuantEcon.

**Comment by jlperla** [comment]
@orangebacked   Thanks!  What lecture did this break on?

**Comment by orangebacked** [comment]
This one! https://python.quantecon.org/finite_markov.html

**Comment by jlperla** [comment]
Sorry, I am a little confused.  I think you mean the julia lectures.  If so then https://julia.quantecon.org/introduction_dynamics/finite_markov.html  doesn't seem to have any issues in the sourcecode for the elcture?  If it is the python lectures then the source is in a different repo I can track down

**Comment by orangebacked** [comment]
I tried to replicate the mistake and it doesn't appear anymore, I'm sorry sometimes julia works in mysterious was (also I didn't clean the workspace so probably there was a conflict something I was running before). Let me know If I can help you with something, I'd be happy to collaborate in this repo.

**Comment by jstac** [comment]
Thanks @orangebacked , all help is appreciated :-)

@jperla is managing this repo and there are usually some open issues you can tackle.  Another option is to convert existing Python lectures into Julia lectures.  But please coordinate with @jlperla if you're going to do that.

**Comment by jlperla** [comment]
Thanks @orangebacked 

I understand what you mean about mysterious julia ways. Sounds like the sort of thing that pops up when you mix packages with Julia. If you did an include on a package (or wrote your own function called `simulate` before using one in quantecon.jl  package was included, then it could cause that sort of issue.
