### ISSUE TITLE
Phantom section in the lecture notes

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#28]
See the section `21 .... more setup` below.

![image](https://user-images.githubusercontent.com/13106721/129314724-8bbb0063-15ad-43be-9bc7-13d562b3bfe2.png)

**Comment by jbrightuniverse** [comment]
This is because of a malformed block of code which escaped too early, thus exposing a julia comment starting with a `#` that thus got converted to a section title.

**Comment by Alim-faraji** [comment]
Solved #31
