### ISSUE TITLE
Julia lectures cannot be compiled on Google colab

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-julia.myst#292]
Hi @jlperla , I tried to launch our Julia lectures on Google Colab using the link on the top right corner of our website,

e.g. this one: https://julia.quantecon.org/getting_started_julia/julia_essentials.html

but the lectures can't be compiled on Google Colab. 

I wonder if there is any better solution to run the Julia lectures on the cloud service.

**Comment by jlperla** [comment]
Thanks @shlff 

Sadly, I think that colab just never happened for Julia.  There were some workarounds a few years ago, but I don't think they are maintainable.  I think we should add in an issue to remove that from the template (which I am unable to do myself).

As for other cloud options, binderhub mostly works, I believe? Try the link on https://github.com/QuantEcon/lecture-julia.notebooks to see what you think.

There are others out there, but not sure if it is possible to launch from a link like this.  We used to have public hubs, but they are not available now, sadly.

**Comment by jlperla** [comment]
I am going to close this as I think Julia running in a non-specialized cloud environment is unlikely in the medium-term.  If colab or alternatives come up, we can revisit.
