### ISSUE TITLE
Installation instructions for building jupyterbook

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#30]
@Alim-faraji  and @jbrightuniverse  and cc @mmcky 

I am not sure if windows is supported yet in jb?  If not, then I would love to have WSL instructions.   I can't figure it out.

I ended up creating a PR with the same environment as the datascience one (see https://github.com/QuantEcon/lecture-julia.myst/pull/29 ) which might be a nice idea for complete consistency in the setups.  We can then copy/paste into this as we have the datascience one up and running.  We can remove some of the extra packages if we wish, but maybe they do no harm.

Maybe someone can look at #29 and maybe take it over and update the instructions and test stuff?  Again, the more consistent with the datascience lectures for the setup/etc. the happier I am.

**Comment by Alim-faraji** [comment]
Jupyter-book [docs ](https://jupyterbook.org/advanced/windows.html#working-on-windows) say some Windows users may experience the nested table of contents problem. However, I didn't have any issues. @jbrightuniverse also compiled all notebooks without any problem. I say we use Windows, without WSL.

**Comment by jlperla** [comment]
Fine with me. And if the nested toc is just something   that just looks weird on windows but is fine when deployed properly, that is totally fine.
