### ISSUE TITLE
Wald-Friedman failing unit tests

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#33]
If you walk through the generated jupyter notebook, you can see `Verifying Output` testset is failing.  

It might simply be that these are due to changes in the random numbers, but we should check against the published version.

@Alim-faraji  Is this the sort of unit test changes you were fixing before?  If so, do we just need to loosen the comparison or change the values?

The first error I get are in the unit tests.
```
Accept x1 if p ≤ 0.35
Continue to draw if 0.35 ≤ p ≤ 0.57

Accept x0 if p ≥ 0.57
Correct: 0.48
Average Cost: 1.32
Average number of trials: 1.39Verifying Output: Test Failed at c:\Users\jesse\Documents\GitHub\lecture-julia.myst\lectures\_build\jupyter_execute\dynamic_programming\wald_friedman.jl:140
  Expression: mean(outcomes) ≈ 0.5
   Evaluated: 0.48 ≈ 0.5
Stacktrace:
 [1] macro expansion
   @ c:\Users\jesse\Documents\GitHub\lecture-julia.myst\lectures\_build\jupyter_execute\dynamic_programming\wald_friedman.jl:140 [inlined]
 [2] macro expansion
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Test\src\Test.jl:1151 [inlined]
 [3] top-level scope
   @ c:\Users\jesse\Documents\GitHub\lecture-julia.myst\lectures\_build\jupyter_execute\dynamic_programming\wald_friedman.jl:135
Verifying Output: Test Failed at c:\Users\jesse\Documents\GitHub\lecture-julia.myst\lectures\_build\jupyter_execute\dynamic_programming\wald_friedman.jl:141
  Expression: ≈(mean(costs), 1.28, atol = 0.01)
   Evaluated: 1.3179999999999998 ≈ 1.28 (atol=0.01)
```

**Comment by Alim-faraji** [comment]
Yes, I changed (or I may say fixed) some unit tests. We can check the output on the last step page by page. But I don't see how can we check each test by comparing it to the published version.

**Comment by jlperla** [comment]
@Alim-faraji  Oh sorry, all I meant was to make sure looking at the pbulished one that this really is just a problem with random variables changing and not a "real" mistake.  I think you can use your judgement on that one.

**Comment by Alim-faraji** [comment]
I changed a lot of unit tests. I checked the graphs and actual outputs to the new generated ones. All seemed fine to me. The unit tests were mostly failing cause they were checking one step in a simulation, which I guess is highly sensitive to the random number generator.

**Comment by Alim-faraji** [comment]
I check this Wald-Friedman failing unit test and fix it as I see fit.

**Comment by jlperla** [comment]
Perfect.  I am only thinking about this one right now.  If you think it just needs a relaxed random number comparison, then that is good enough for me!
