### ISSUE TITLE
Caching julia artifacts to speed up CI

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#39]
@mmcky  I just wanted to write down a few notes, but this can be done at your own time (if ever :-)

The Julia artifacts  (in `~/.julia/artifacts`) can be cached fairly easily, which is all of the binary stuff it would need to download.  See https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/blob/main/.github/workflows/CI.yml#L24-L33  as an example, which hashes based on the project/manifest and is the standard CI one.

This stuff could probably be added below https://github.com/QuantEcon/lecture-julia.myst/blob/main/.github/workflows/cache.yml#L34-L39  without too much trouble.

Otherwise, it is a little harder to cache too much in the julia setup, but not impossible.  My guess is that the jupyter execution cache itself would dominate anything else in the near-term.

The CI speed of package recompilation should also be getting better in Julia 1.7 and with some new pacakge updates

**Comment by mmcky** [comment]
thanks @jlperla for these notes. 

I think the setup is now a lot quicker than when I made that comment before re: load times setting up the environment. I think `low priority` is a good priority level. Thanks for jotting these down.

**Comment by jlperla** [comment]
Closing since this doesn't seem to be an issue at this point with julia updates.  We can revisit later.
