### ISSUE TITLE
Turn on the execution

### ISSUE THREAD

**Issue by Alim-faraji** [QuantEcon/lecture-julia.myst#4]
Further down the road, we should turn the execution of notebooks on. 

https://github.com/QuantEcon/lecture-julia.myst/blob/32011e54813b678d7b729c33bc46cd92b09435f2/lectures/_config.yml#L7

**Comment by mmcky** [comment]
Absolutely. But in the short term I recommend working with it off for checking the `html` generation as iterating is a lot quicker. 

We will also need:

- [ ] setup a julia environment with the packages
- [ ] turn on execution to check outputs etc

**Comment by mmcky** [comment]
Also #2 needs to be resolved first for execution to work if there is any code coming in from a file
