### ISSUE TITLE
Header missing for Julia setup in 13.1.1

### ISSUE THREAD

**Issue by jbrightuniverse** [QuantEcon/lecture-julia.myst#42]
There's nothing separating the codecov section and the Julia section in [Packages, Testing, and CI lecture](https://github.com/QuantEcon/lecture-julia.myst/blob/main/lectures/software_engineering/testing.md). This was previously present and seems to have been accidentally omitted. (Also missing from notebooks).

**Comment by jlperla** [comment]
This section will be completely rewritten with the updates in the engineering infrastructure.
