### ISSUE TITLE
46.6.1: click to show hides code output that is supposed to be displayed

### ISSUE THREAD

**Issue by jbrightuniverse** [QuantEcon/lecture-julia.myst#48]
[https://quantecon.github.io/lecture-julia.myst/multi_agent_models/markov_perf.html#id8](https://quantecon.github.io/lecture-julia.myst/multi_agent_models/markov_perf.html#id8)

The output is auto-displayed in the original lectures so perhaps this should be changed?

**Comment by jlperla** [comment]
I think this is a "by design" in jupyterbook.
