### ISSUE TITLE
Do we still need gr(fmt = :png);?

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#65]
What is the default at this point, and is this purely to save on space for executed files?

**Comment by jlperla** [comment]
I believe we do.  Tried one of the plots with a large number of points and the size went up a factor of 10x.

But we probably can remove them for a lot of the pages at some point.

**Comment by jlperla** [comment]
Actually, we can put the `fmt=:png` argument on individual plot calls.  For example, `plot(x, y; , fmt=:png)` if it would be a massive figure in a notebook.  There are probably very few of these.

**Comment by jlperla** [comment]
My suggestion for finding the problem children is the following:
- get rid of the gr(fmt = :png) globally.  In every file
- Regenerate all of the notebooks with a clean juptyerbook build
- Then go back and try to figure out which files were enormous and/or which notebooks are enormous.  The standard for "enormous" here you can figure out on your own, but > 3 mb for an individual file seems pretty large.
- I am not 100% sure how to access this, but maybe you go to lectures/build/jupyter_execute and then see the sizes of all of the ipynb files that it generates?  Or maybe the generated .svg and/or .svg ones it generaets?  Look for big ones, and add in the plot(...; fmt = :png) for those troublemakers.
- If I had to guess, there will be less that 10-15 of these where it really matters.  The rest we can keep in the nicer vectorized plots.

**Comment by jbrightuniverse** [comment]
Most files are now < 1mb.
A handful are between 1 and 2mb.
One is 2.2mb, one is 2.7mb.

And then this one:
![image](https://user-images.githubusercontent.com/30967260/133731916-cd44f3bf-f2e7-4805-9cf4-a7fc965eda05.png)
this one needs to be altered for sure. Might be able to go back and do all the >2mb ones too.

**Comment by jlperla** [comment]
Great! The 2.7 are fine. Let's just change this big one and then ship it!

**Comment by jbrightuniverse** [comment]
For `additive_functionals`, one plot composes 5MB alone so I think I should be able to just change this one only, and then we should be good to go. I'll leave the other ones as-is for now using 3mb as the general cutoff rule.

**Comment by jlperla** [comment]
Can we close this now?

**Comment by jbrightuniverse** [comment]
This can be closed.
