### ISSUE TITLE
Comment out all unit test checks that are random

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#72]
The main purpose of those unit tests was in the initial port to jupinx, and in the new port to jupyterbook.  At this point, they are more trouble than they are worth if they are randomized.

So we should basically go through and just comment them out - leaving unit test checks that are fully deterministic alone.
This will become an especially big problem with Julia 1.7 since I believe they changed the default random number generator.

To do this, do a global search for `@test` in vscode and just go through them quickly.  How to know if they are random or not?
- If any of it seems to refer to something called "shocks" etc. it was probably random. 
- If  it is a comparison with any sort of `atol` or `rtol` then it probably was random and we loosened it to just get the basic tests passing as a sanity check.

I think we can lean on the side of turning off more than less at this point, but once we upgrade or run into problems we can just start turning them off as they cause isseues.

@Alim-faraji  and @jbrightuniverse

**Comment by Alim-faraji** [comment]
I tried to comment out all random tests in [here](https://github.com/QuantEcon/lecture-julia.myst/pull/74). I replaced `@test` to `#test`.

**Comment by Alim-faraji** [comment]
I think we can close this issue now.
