### ISSUE TITLE
Fix general warnings

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#79]
```
/home/runner/work/lecture-julia.myst/lecture-julia.myst/lectures/dynamic_programming_squared/dyn_stack.md:838: WARNING: Could not lex literal_block as "julia". Highlighting skipped.
368
writing output... [100%] zreferences                                           
369
/home/runner/work/lecture-julia.myst/lecture-julia.myst/lectures/getting_started_julia/julia_essentials.md:23: WARNING: Could not lex literal_block as "julia". Highlighting skipped.
/home/runner/work/lecture-julia.myst/lecture-julia.myst/lectures/software_engineering/tools_editors.md:170: WARNING: Non-consecutive header level increase; 2 to 4 [myst.header]
```

**Comment by Alim-faraji** [comment]
@mmcky Do you have any idea on these warnings?
`/home/runner/work/lecture-julia.myst/lecture-julia.myst/lectures/dynamic_programming_squared/dyn_stack.md:838: WARNING: Could not lex literal_block as "julia". Highlighting skipped.
91
/home/runner/work/lecture-julia.myst/lecture-julia.myst/lectures/getting_started_julia/julia_essentials.md:23: WARNING: Could not lex literal_block as "julia". Highlighting skipped.`

Other lectures have same code block. But they don't cause any warnings.

**Comment by Alim-faraji** [comment]
Also, the `contents` [block](https://github.com/QuantEcon/lecture-julia.myst/blame/main/lectures/getting_started_julia/julia_essentials.md#L23) doesn't seem to produce any table of contents. 
````
```{contents} Contents
24
:depth: 2
25
```
````

<img width="922" alt="Screen Shot 2021-08-19 at 1 08 32 PM" src="https://user-images.githubusercontent.com/71057115/130136846-4b5262c6-3024-4924-b2d2-409de9bf3684.png">

<img width="850" alt="Screen Shot 2021-08-19 at 1 08 46 PM" src="https://user-images.githubusercontent.com/71057115/130136876-639c4dfd-f253-47b4-880f-fd330b445d2a.png">

Is it something we want? If so, we should drop the `contents` block altogether.

**Comment by jlperla** [comment]
I am planning to rewrite this section anyways.  So lets leave this open and see if the issues disappear.

**Comment by Alim-faraji** [comment]
Sounds good. However non of the pages have a table of content.

**Comment by Alim-faraji** [comment]
Also, 
```
/home/runner/work/lecture-julia.myst/lecture-julia.myst/lectures/dynamic_programming_squared/dyn_stack.md:838: WARNING: Could not lex literal_block as "julia". Highlighting skipped. 
```

[This](https://github.com/QuantEcon/lecture-julia.myst/blame/main/lectures/dynamic_programming_squared/dyn_stack.md#L838) is causing the warning:
````
```{math}
839
:label: law-motion
840
841
\begin{bmatrix} \tilde y_{t+1} \\
842
q_{1t+1} \end{bmatrix} = \begin{bmatrix} A - BF & 0 \\
843
0  & 1 \end{bmatrix}  \begin{bmatrix} \tilde y_{t} \\
844
q_{1t} \end{bmatrix} + \begin{bmatrix} 0 \cr 1 \end{bmatrix} x_t
845
```
````

is still an issue. Again we have the same block on other pages that compile without any warnings. For example [here](https://github.com/QuantEcon/lecture-julia.myst/blame/main/lectures/continuous_time/covid_sde.md#L196).

**Comment by jlperla** [comment]
Maybe the `\cr` isn't valid?  Change it to `\\` ?

**Comment by mmcky** [comment]
hey @Alim-faraji the local `contents` isn't supported in our theme as they are now in the RHS navigation column in `jupyter-book` with `on this page`

https://python.quantecon.org/linear_algebra.html

**Comment by mmcky** [comment]
the 

```
WARNING: Could not lex literal_block as "julia".
```

would be linked to a block such as `code` (rather than `code-cell`) or `literal-include`. Not sure why it thinks it is related to a `math` block. Hmm I won't get the chance to look at this today but will look over the weekend if you're not successfull.

**Comment by Alim-faraji** [comment]
Thanks. Yes I can replicate it locally.

**Comment by Alim-faraji** [comment]
> Maybe the `\cr` isn't valid? Change it to `\\` ?

Didn't change anything.

**Comment by Alim-faraji** [comment]
I'm closing this issue and opening a new one for `/home/runner/work/lecture-julia.myst/lecture-julia.myst/lectures/dynamic_programming_squared/dyn_stack.md:838: WARNING: Could not lex literal_block as "julia". Highlighting skipped.
368` specifically.
