### ISSUE TITLE
Remove unnecessary packages (and upgrade if appropriate)

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#97]
- [x] I think we can remove the following packages from the project file,
```julia
] rm TimerOutputs SparsityDetection PkgTemplates KrylovKit Compat ModelingToolkit Expokit Flux InstantiateFromURL LinearOperators PkgTemplates Revise SparseDiffTools SparsityDetection LazyArrays FillArrays ExponentialUtilities HTTP BlockBandedMatrices StatsModels StatsBase LaTeXStrings 
```
There may be a typo or two?
- [x] Maybe look at `Project.toml` and see if there are other packages not used included directly in it.  For that you can just search in VS Code for the packagename and see if there is ever a `using` of it.  If not, remove it.
- [x] After this operation, I would save the resulting `Project.toml` and `Manifest.toml` to the branch.
- [x] You want to ensure that it didn't end up significantly downgrading anything important.  For example, the Plots, GR, Distributions, NLsolve, and Optim should be at the maximum version.  If not, then try to `] up Plots GR Distributions NLsolve Optim` etc. to try to get it to have those at the maximum version.
- [x] If you get something good, then commit it to the branch so you don't lose it.
- [x] Finally, try to do a more general `] up` and see if you can get things to an even higher version now that we have removed some constraints.  There is a chance, though, that it will choose a suboptimal solution for us (e.g. one that downgrades those critical packages).  If so, then reject it and maybe just tinker with it to try to get a functional set.

If this is acting weird, then you can delete the Manifest.toml, reopen a julia repo, and do `] resolve` or something like that to have it solve the constrained optimization problem with the dependencies again.

Removing those packages will help us keep the installation smaller and make future upgrades easier.

- [x] OK, now finally, do a `jb clean lectures --all` and then do a full notebook rebuild.  DOublecheck that there aer no build errors.
  - If there are any packages that shouldn't have been removed and are now failing for some `using` then add them back.

**Comment by jbrightuniverse** [comment]
Package changes recorded in `issue97` branch; I was able to remove some additional packages and bump many of them; one bump did end up downgrading the dependency-only (not inside `Project.toml`) package `LoopVectorization` by one patch from `0.12.66` to `0.12.55` but that was the only downgrade.

**Comment by jlperla** [comment]
Sounds successful! Is everything passing the tests, no warnings with a clean build, etc?

**Comment by jbrightuniverse** [comment]
No new warnings/errors were generated. Would I get errors about failing tests in the terminal?

There's still the three warnings with `could not lex literal_block` and `undefined label: upgrading_julia` but those were there before.

**Comment by jlperla** [comment]
I think if you did a clean build and there was no other issues we would see a failure? Is that still correct @mmcky or would #84 not being merged change things?

Regardless, I think you should merge it @jbrightuniverse and close the issue.

**Comment by mmcky** [comment]
Just `FYI` it is worth checking the errors on this repo at this stage as `-W` is not enabled to halt execution due to those mysterious lexer warnings on `julia` highlighting. https://github.com/QuantEcon/lecture-julia.myst/pull/84

**Comment by jlperla** [comment]
Thanks @mmcky. How do we check errors then?

**Comment by mmcky** [comment]
either from local builds while making changes or you can check the `github action` such as:

https://github.com/QuantEcon/lecture-julia.myst/runs/3514506876

and checking the 'Build HTML' workflow step for its output of any warnings.

**Comment by mmcky** [comment]
It's not optimal -- much better with `-W` enabled. I should get back to that lexer warning (but probably will be next week at this stage)
